"""Generate ``nexcoder/ui/src/data/skills.ts`` from the backend registry.

The frontend's ``FALLBACK_SKILLS`` list mirrors the backend's
``skills_registry``. Run this script after adding or renaming a skill so
the dev-mode fallback stays in sync with the source-of-truth directory.
"""

import os
import sys

# Add the nexcoder directory to the path so we can import skills_registry
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))
NEXCODER_PATH = os.path.join(PROJECT_ROOT, "nexcoder")
if NEXCODER_PATH not in sys.path:
    sys.path.insert(0, NEXCODER_PATH)

from nexcoder.agent.skills_registry import get_skills, get_skill_categories  # noqa: E402

# Skills we don't want to surface in the dev fallback (kept on disk for
# the agent to invoke but not in the UI picker).
_HIDDEN_IDS: set[str] = set()


def _esc(value: str) -> str:
    return (value or "").replace("\\", "\\\\").replace('"', '\\"')


def main() -> None:
    skills = get_skills()
    categories = get_skill_categories()

    out_dir = os.path.join(PROJECT_ROOT, "nexcoder", "ui", "src", "generated")
    os.makedirs(out_dir, exist_ok=True)
    out_path = os.path.join(out_dir, "skills.ts")

    lines: list[str] = []
    lines.append("// Auto-generated by generate_skills.py — do not edit by hand.")
    lines.append("// The runtime fetches skills via the bridge; this list is the")
    lines.append("// dev-mode fallback used when the bridge is not connected.")
    # This file lives in src/generated/ — the type module sits one
    # directory up under src/data/, so the import path is relative
    # to the generated file's location.
    lines.append("import type { Skill, SkillCategory } from '../data/skills-types';")
    lines.append("")
    lines.append("export const GENERATED_SKILLS: Skill[] = [")
    for s in skills:
        if s["id"] in _HIDDEN_IDS:
            continue
        lines.append(
            "  { id: \""
            + _esc(s["id"])
            + "\", label: \""
            + _esc(s["label"])
            + "\", icon: \""
            + _esc(s["icon"])
            + "\", category: \""
            + _esc(s["category"])
            + "\", description: \""
            + _esc(s["description"])
            + "\", shortcut: \""
            + _esc(s.get("shortcut", ""))
            + "\" },"
        )
    lines.append("];")
    lines.append("")
    lines.append("export const GENERATED_CATEGORIES: SkillCategory[] = [")
    for c in categories:
        lines.append(
            "  { id: \""
            + _esc(c["id"])
            + "\", label: \""
            + _esc(c["label"])
            + "\", description: \""
            + _esc(c["description"])
            + "\", icon: \""
            + _esc(c["icon"])
            + "\", order: "
            + str(c["order"])
            + " },"
        )
    lines.append("];")
    lines.append("")

    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"Generated {len(skills)} skills and {len(categories)} categories at {out_path}")


if __name__ == "__main__":
    main()
