"""DebugMode — error-focused diagnosis and fix mode, now agentic.

The mode still uses :class:`ErrorParser` to extract a structured error
context from the terminal output, but the actual fix is now generated by
the Hermes agent loop: the model reads the offending file, searches for
related call sites, and either writes the fix or emits a diff block.
"""

import logging
from typing import Any, Callable

from nexcoder.agent.agentic_runner import AgenticRunner
from nexcoder.agent.error_parser import ErrorParser
from nexcoder.agent.mode_profiles import DEBUG_PROFILE

logger = logging.getLogger(__name__)


class DebugMode:
    """Debug mode — locates the root cause and produces a targeted fix."""

    def __init__(self) -> None:
        self._runner = AgenticRunner(DEBUG_PROFILE)
        self._error_parser = ErrorParser()

    def execute(
        self,
        prompt: str,
        context: dict[str, Any],
        history: list[dict[str, str]],
        callbacks: dict[str, Callable],
    ) -> dict[str, Any]:
        on_status = callbacks.get("on_status", lambda s, m: None)
        on_status("running", "Parsing errors...")

        # Enrich the prompt with parsed error context. The model still has
        # to verify by reading the file via tools, but a short summary
        # primes it to know what the failure looks like.
        error_output = context.get("errorOutput", "")
        parsed_errors = self._error_parser.parse(error_output) if error_output else []
        if parsed_errors:
            error_context = self._error_parser.format_for_ai(parsed_errors)
            prompt = (
                f"{error_context}\n\n"
                f"User request: {prompt}\n\n"
                "Please:\n"
                "1. Explain the root cause\n"
                "2. Provide the fix as a write_file call or diff block"
            )

        return self._runner.run(prompt, context, callbacks)
