/**
 * Static catalog of AI modes and skill metadata.
 *
 * The mode list is the source of truth for the five built-in behaviours
 * (ask / edit / agent / debug / review). Skills are loaded from the
 * backend at runtime via {@link fetchSkills}; the generated file under
 * ``../generated/skills.ts`` is the build-time mirror of the registry
 * and is the dev-mode fallback when the bridge is not connected.
 */
import {
  MessageCircle,
  Pencil,
  Bot,
  Bug,
  ShieldCheck,
  Radar,
  Layout,
  FlaskConical,
  ClipboardCheck,
  Sparkles,
  GitBranch,
  Monitor,
  Gauge,
  Cable,
  Shield,
  Workflow,
  Rocket,
  ListChecks,
  Layers,
  FileText,
  Lightbulb,
  MessagesSquare,
  HelpCircle,
  BookOpen,
  PackageOpen,
  Database,
  BookMarked,
  Activity,
  Compass,
  Plug,
  Box,
  type LucideIcon,
} from 'lucide-react';

export type { Skill, SkillCategory } from './skills-types';
import type { Skill, SkillCategory } from './skills-types';

import { GENERATED_SKILLS, GENERATED_CATEGORIES } from '../generated/skills';

export type ModeId = 'ask' | 'edit' | 'agent' | 'debug' | 'review';

export interface ModeEntry {
  id: ModeId;
  label: string;
  icon: LucideIcon;
  description: string;
  color: string;
  shortcut: string;
}

export const MODES: ModeEntry[] = [
  {
    id: 'ask',
    label: 'Ask',
    icon: MessageCircle,
    description: 'Read-only Q&A — agent inspects files to answer your question.',
    color: 'var(--accent-purple)',
    shortcut: '/ask',
  },
  {
    id: 'edit',
    label: 'Edit',
    icon: Pencil,
    description: 'Targeted edits to the active file with diff approval.',
    color: 'var(--accent-blue, #60a5fa)',
    shortcut: '/edit',
  },
  {
    id: 'agent',
    label: 'Agent',
    icon: Bot,
    description: 'Autonomous multi-step agent — plans, edits, runs commands.',
    color: 'var(--accent-green)',
    shortcut: '/agent',
  },
  {
    id: 'debug',
    label: 'Debug',
    icon: Bug,
    description: 'Diagnose errors, stack traces, generate targeted fixes.',
    color: 'var(--accent-orange, #fb923c)',
    shortcut: '/debug',
  },
  {
    id: 'review',
    label: 'Review',
    icon: ShieldCheck,
    description: 'Thorough code audit — security, bugs, performance, quality.',
    color: 'var(--accent-cyan, #22d3ee)',
    shortcut: '/review',
  },
];

// lucide-react icon registry. The backend returns icon *names* as
// strings, so the UI maps each name to the actual component.
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  MessageCircle,
  Pencil,
  Bot,
  Bug,
  ShieldCheck,
  Radar,
  Layout,
  FlaskConical,
  ClipboardCheck,
  Sparkles,
  GitBranch,
  Monitor,
  Gauge,
  Cable,
  Shield,
  Workflow,
  Rocket,
  ListChecks,
  Layers,
  FileText,
  Lightbulb,
  MessagesSquare,
  HelpCircle,
  BookOpen,
  PackageOpen,
  Database,
  BookMarked,
  Activity,
  Compass,
  Plug,
  Box,
};

// Dev-mode fallback used when the bridge is not connected. Mirrors the
// backend's skills registry; regenerated by `python generate_skills.py`.
export const FALLBACK_SKILLS: Skill[] = GENERATED_SKILLS;
export const FALLBACK_CATEGORIES: SkillCategory[] = GENERATED_CATEGORIES;
